# Generated by Django 4.0 on 2021-12-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='document.type'),
        ),
    ]
